### ISSUE TITLE
[BUG] Dupe Glitch

### ISSUE THREAD

**Issue by snailinapail** [Kqmu/HybridSMP#1]
**Describe the bug**
The bug is a dupe glitch that involves the backpack mod, dead body mod, cosmetic armor mod, and the mod that lets you sort items in your inventory and lets you export/import items into your inventory(I don't know the exact name of it.)

**To Reproduce**
1. Die lol. (When you respawn, you will still have your cosmetic armors on.)
2. Press U and go to a body profile that has the button "additional items" available. When you go to additional items, a copy of your cosmetic armors should be in the body.
3. Click the export button at the top of your inventory.
4. Profit.

**Expected behavior**
You will be able to dupe powerful items basically.

**Additional context**
If you have a backpack in your cosmetic armor slot when you do this glitch, you will have two backpacks that are interconnected which then makes another dupe glitch. For example, if you put a diamond in one backpack, it will show up in the other backpack and be duped. Once you dye one of the backpacks a different color, the glitch won't work anymore.

**Comment by Kqmu** [comment]
Bug is between Quark and Sophisticated backpacks, with no real fix. I'll look into ways of fixing it sooner or later

**Comment by Kqmu** [comment]
https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/97 [Possible Fix]
Might remove Sophisticated Backpacks.
